### ISSUE TITLE
Enhancement: make homepage UX better

### ISSUE THREAD

**Issue by takanome-dev** [xml-wizard/huetiful#70]
People like what they see so a pretty landing page is a necessary aesthetic. I think they're plenty of landing page examples out there for libraries but here's what I had in mind:
-  A flowfield coverpage that has shifting colors (kinda makes the project goal obvious that its about color). This could be preferably full viewport.
-  A description of the library capabilities, a getting started section and at the footer we can put some statistics about the project e.g stargazers, forks and contributors.

![Screenshot_20231103_124108_com.sec.android.app.sbrowser.jpg](https://github.com/prjctimg/huetiful/assets/104896135/4bf148db-f23e-47c7-8553-4399ce853cbd)

I've attached an example landing page above. Feel free to make suggestions

**Comment by foss2cyber** [comment]
@takanome-dev Want to get started on this. Can you elaborate a bit on the shifting colours part ?

**Comment by takanome-dev** [comment]
> @takanome-dev Want to get started on this. Can you elaborate a bit on the shifting colours part ?

Thanks for your interest @foss2cyber. This issue has been extracted from this discussion https://github.com/prjctimg/huetiful/discussions/62#discussioncomment-7465683

@prjctimg can you provide more info here?

**Comment by prjctimg** [comment]
> > @takanome-dev Want to get started on this. Can you elaborate a bit on the shifting colours part ?
> 
> Thanks for your interest @foss2cyber. This issue has been extracted from this discussion [#62 (comment)](https://github.com/prjctimg/huetiful/discussions/62#discussioncomment-7465683)
> 
> @prjctimg can you provide more info here?

Of course!

@foss2cyber The shifting colours part is simple since the library already has such a utility for that, `hueShift()` [see the docs under 'Palette utilities'](https://huetiful-docs.vercel.app/blog/palette-utilities). It returns an array of hueshifted colors from a single base color. 

Now that we have our array of colors from running the `hueshift()` We can then pass each particle of our flowfield with a color from the array. For more information about flowfields see [Dan Shiffman's original implementation here](https://lramrz.com/2016/12/flow-field-in-p5js/). It uses p5js

**Comment by foss2cyber** [comment]
> > > @takanome-dev Want to get started on this. Can you elaborate a bit on the shifting colours part ?
> > 
> > 
> > Thanks for your interest @foss2cyber. This issue has been extracted from this discussion [#62 (comment)](https://github.com/prjctimg/huetiful/discussions/62#discussioncomment-7465683)
> > @prjctimg can you provide more info here?
> 
> Of course!
> 
> @foss2cyber The shifting colours part is simple since the library already has such a utility for that, `hueShift()` [see the docs under 'Palette utilities'](https://huetiful-docs.vercel.app/blog/palette-utilities). It returns an array of hueshifted colors from a single base color.
> 
> Now that we have our array of colors from running the `hueshift()` We can then pass each particle of our flowfield with a color from the array. For more information about flowfields see [Dan Shiffman's original implementation here](https://lramrz.com/2016/12/flow-field-in-p5js/). It uses p5js

Thanks a lot, mate!

**Comment by prjctimg** [comment]
No worries! 

@foss2cyber Here's a rough pseudocode example for how you could initialize the color generation:

```
// Importing the colors() and hueShift() utils
import { colors,hueShift } from 'huetiful-js'


// We want an array of  colors of value 400 from the TailwindCSS default palette. This means blue-500, red-500 etc

let baseColors = colors('all','400')

const { map } = Array


// This will make a nested array of hueshifted colors with each array containing 10 elements in the hex format
let hueShiftedPalette = map(baseColors,(color) => hueShift(color,{num = 10,hueStep = 5},true))

```

**Comment by foss2cyber** [comment]
> No worries!
> 
> @foss2cyber Here's a rough pseudocode example for how you could initialize the color generation:
> 
> ```
> // Importing the colors() and hueShift() utils
> import { colors,hueShift } from 'huetiful-js'
> 
> 
> // We want an array of  colors of value 400 from the TailwindCSS default palette. This means blue-400, red-400 etc
> 
> let baseColors = colors('all','400')
> 
> const { map } = Array
> 
> 
> // This will make a nested array of hueshifted colors with each array containing 10 elements in the hex format
> let hueShiftedPalette = map(baseColors,(color) => hueShift(color,{num = 10,hueStep = 5},true))
> ```

Thanks. Gonna try this out. Let's see how it goes...!

**Comment by prjctimg** [comment]
This issue has been resolved, by @adarshswaminath in this commit at the docs repository.  [See the preview here](https://huetiful-docs-4h0x7zlyi-my-team-84794c1e.vercel.app/)

**Comment by foss2cyber** [comment]
> This issue has been resolved, by @adarshswaminath in this commit at the docs repository. [See the preview here](https://huetiful-docs-4h0x7zlyi-my-team-84794c1e.vercel.app/)

Ah....I was too late it seems. I just made a PR with some UI changes.

**Comment by prjctimg** [comment]
> > This issue has been resolved, by @adarshswaminath in this commit at the docs repository. [See the preview here](https://huetiful-docs-4h0x7zlyi-my-team-84794c1e.vercel.app/)
> 
> @prjctimg Ah....I was too late it seems. I just made a PR with some UI changes. 

@foss2cyber No worries! The issue was temporarily closed to keep the issues trimmed. 

Thank you for the changes! I reviewed the build logs and it seems like your deployment failed because of a `yarn install` based error . Here's the screenshot for the build error: @takanome-dev  is working on setting up the GitHub Action for Vercel deployment so that all contributors can have access to the build logs. ![Screenshot_20231121-164523.jpg](https://github.com/prjctimg/huetiful/assets/104896135/3504e5a4-716d-41c1-b8c5-205651706058)



Note that the last part mentions about the lockfile being prohibited from modification during dependancy installations. Is there a way to resolve the dependancy issues?

**Comment by prjctimg** [comment]
Thank you @foss2cyber  and @adarshswaminath for the redesign! We'll revisit and iterate on the design with more complex visuals and accessibility improvements. 

Are we all satisfied with the design 🚀

@H-K-R @arcVaishali @Cubic-ctrl @takanome-dev

**Comment by prjctimg** [comment]
Please note any design inconsistencies and we'll resolve them by building an as per requirement design system.


#### Some of the errata and changes I think would be beneficial are:

- At the end of the page there's a declaration saying `Tailwind starter theme.
- The primary and secondary colors are clashing. One appears more saturated than the other. Thus we need to define a palette. We could use the logo colors as a starting point.In the future we'll make our palette color blind safe and more adaptive. 
- Inconsistencies in padding. Some elements seem to have more padding than others.
- Do we need a newsletter? If no then we should probably deprecate that component, right? 
- Can we add a bit of animations and transitions to the page. For example easing in components as the user scrolls.
-  Can we add a "Star this project" or similar button on the homepage. Lol, 😂 Okay so our stats may not really worth that much bragging but we should include them still. We can use [badges from Shields](https://shields.io)
- There's a redundant description below the `Utilities` heading which is similar to the description on the cover page.



Please feel free to suggest changes and better approaches to a standard design strategy we can use throughout the docs 🙏. 


 I'll share some ideas of using generative art for our backgrounds and example websites where those technics are used. We're after all, a project about color so we should flex a little 😁

**Comment by prjctimg** [comment]
Please note any design inconsistencies and we'll resolve them by building an as per requirement design system.


#### Some of the errata and changes I think would be beneficial are:

- At the end of the page there's a declaration saying `Tailwind starter theme.
- The primary and secondary colors are clashing. One appears more saturated than the other. Thus we need to define a palette. We could use the logo colors as a starting point.In the future we'll make our palette color blind safe and more adaptive. 
- Inconsistencies in padding. Some elements seem to have more padding than others.
- Do we need a newsletter? If no then we should probably deprecate that component, right? 
- Can we add a bit of animations and transitions to the page. For example easing in components as the user scrolls.
-  Can we add a "Star this project" or similar button on the homepage. Lol, 😂 Okay so our stats may not really worth that much bragging but we should include them still. We can use [badges from Shields](https://shields.io)
- There's a redundant description below the `Utilities` heading which is similar to the description on the cover page.

- And can we add a contributors component so that the open source community can know your commitment to the craft 💻.


##### Conclusion ⛓️

Please feel free to suggest changes and better approaches to a standard design strategy we can use throughout the docs 🙏. 


 I'll share some ideas of using generative art for our backgrounds and example websites where those technics are used. We're after all, a project about color 🎨 so we should flex a little 😁

**Comment by foss2cyber** [comment]
@prjctimg For choosing a **better color palette** and **typography**, I suggest taking a look at [this site here](https://www.realtimecolors.com/) & [this article here](https://webflow.com/blog/best-color-combinations). Could also take a look at [BarbaJS](https://barba.js.org/docs/getstarted/useful-links/) for really dope **animations** we could use.
Also, **Feather Icons** are :+1: .
I'll get started on the padding inconsistencies.
We should definitely include a **star this project** button to the homepgae & the  **contributors component** sounds cool. 
What do y'all think? @adarshswaminath @takanome-dev @H-K-R

**Comment by adarshswaminath** [comment]
yeah, we need to correct the paddings of some elements, and the changes suggested by @prjctimg  are nice. It's good to have some transition; it makes it better. We can change icons if they look chunky, clumsy, and generic. I think currently, we don't need the newsletter component. Please remove the Tailwind starter theme text. Additionally, I believe we need to consider changing the color themes because they are clashing. Also, we need to make sure the color theme is suitable for both dark and light themes. @foss2cyber  For easing in components as the user scrolls , we can use libraries like AOS or Framer Motion, or any other. It's cool to add a 'star this project' button to the homepage, and the contributors component sounds cool.

**Comment by foss2cyber** [comment]
@prjctimg   Here's what I liked:

![Screen Shot 2023-11-24 at 17 06 35](https://github.com/prjctimg/huetiful/assets/78159236/c7959ced-400d-4978-b5c6-6b1772a2c425)
 
![Screen Shot 2023-11-24 at 17 11 07](https://github.com/prjctimg/huetiful/assets/78159236/c54443b9-183b-4f54-b642-e6987c2a7b05)

![Screen Shot 2023-11-24 at 17 11 27](https://github.com/prjctimg/huetiful/assets/78159236/30623570-4946-4967-a4e1-3d3164a3b58e)

![Screen Shot 2023-11-24 at 17 11 30](https://github.com/prjctimg/huetiful/assets/78159236/92882fde-0f98-4f16-9ffa-3659d99cc367)

![Screen Shot 2023-11-24 at 17 11 33](https://github.com/prjctimg/huetiful/assets/78159236/d812bbd5-5ea8-4fa7-9fe9-f480b9ca3189)

![Screen Shot 2023-11-24 at 17 11 37](https://github.com/prjctimg/huetiful/assets/78159236/23c20b1d-0f64-49ba-91b2-423c0e0c3e34)

![Screen Shot 2023-11-24 at 17 11 41](https://github.com/prjctimg/huetiful/assets/78159236/3eb7bc59-a44f-41d3-9c15-d643eff4cf4b)

![Screen Shot 2023-11-24 at 17 11 46](https://github.com/prjctimg/huetiful/assets/78159236/3b894362-e177-4580-a8c7-545ca8f16f97)

![Screen Shot 2023-11-24 at 17 11 50](https://github.com/prjctimg/huetiful/assets/78159236/c5b12608-b54d-44e5-9b68-2f7b1c2e6a8d)

![Screen Shot 2023-11-24 at 17 10 59](https://github.com/prjctimg/huetiful/assets/78159236/5bf4d8a7-ebda-4392-b06e-0bb7595cbec5)

![Screen Shot 2023-11-24 at 17 10 48](https://github.com/prjctimg/huetiful/assets/78159236/69565050-f1ab-4fe9-9e5b-57897c55a7b3)

![Screen Shot 2023-11-24 at 17 10 52](https://github.com/prjctimg/huetiful/assets/78159236/22210f07-505f-4c02-bc45-9f3b2531492f)

**Comment by prjctimg** [comment]
@foss2cyber I see that the blue is popular so maybe we can use a pastel version of it as our primary color or the color to CTAs
And let's proceed with a pastel purple as our accent color. 

We'll finalize the palette option tonight.

**Comment by prjctimg** [comment]
@foss2cyber Well, I guess that's the poll.  We can proceed with the palette chosen.

**Comment by adarshswaminath** [comment]
> @prjctimg Here's what I liked:
> 
> ![Screen Shot 2023-11-24 at 17 06 35](https://private-user-images.githubusercontent.com/78159236/285446213-c7959ced-400d-4978-b5c6-6b1772a2c425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDYyMTMtYzc5NTljZWQtNDAwZC00OTc4LWI1YzYtNmIxNzcyYTJjNDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYTU0MWNlODRlYmMxNjcyOGZlMWFjMzBmMmFmOWQ0NzQyYjRlZmNkYmY1MGI2N2M4NWY2YTYyOWRkMzJlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PHCXeAQ0WZ58mqGgxEJ8vHRJzyMjDcroBuKcnzOia08)
> 
> ![Screen Shot 2023-11-24 at 17 11 07](https://private-user-images.githubusercontent.com/78159236/285447063-c54443b9-183b-4f54-b642-e6987c2a7b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwNjMtYzU0NDQzYjktMTgzYi00ZjU0LWI2NDItZTY5ODdjMmE3YjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYzliMWZiZGY0MmE3MDFhNjE3NDg3NjQwNzhlNGNlMGQyZWE4ZGE3YWY0ODY5OWFkZTk1YTM2ODc3YmY3ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a4JbTdf2Hg46L9H8UBStGeS-X43j0WgWdc2uP8UzJBE)
> 
> ![Screen Shot 2023-11-24 at 17 11 27](https://private-user-images.githubusercontent.com/78159236/285447072-30623570-4946-4967-a4e1-3d3164a3b58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwNzItMzA2MjM1NzAtNDk0Ni00OTY3LWE0ZTEtM2QzMTY0YTNiNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDI1NDA4YzI2YWNhNWM3YmZjMDhjNDJkMGZhNWFkZGU0YjM1YjBkZDEwZDI0NGRkOTlhNDNjODI5NTZlOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WxafgWtN3FOvUYLyQosKDGX83VJP-dr36hlaeaDLv_M)
> 
> ![Screen Shot 2023-11-24 at 17 11 30](https://private-user-images.githubusercontent.com/78159236/285447077-92882fde-0f98-4f16-9ffa-3659d99cc367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwNzctOTI4ODJmZGUtMGY5OC00ZjE2LTlmZmEtMzY1OWQ5OWNjMzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNzJmYzY5ZTRlNDRiMWM0NDE1YmU3N2UyZTRkY2M3MDgwNmY1MjA2MjhiNGVkNGFkNmIwYzkyMjAwZGFkOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BrIqGUcraDM4J4jp3LLOzfej2wzF0GNA-IFWJTbGKKg)
> 
> ![Screen Shot 2023-11-24 at 17 11 33](https://private-user-images.githubusercontent.com/78159236/285447082-d812bbd5-5ea8-4fa7-9fe9-f480b9ca3189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwODItZDgxMmJiZDUtNWVhOC00ZmE3LTlmZTktZjQ4MGI5Y2EzMTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOGUwZDRkMmIwYWFmNWFlZTU1ZWI1MmUwYmNmOTM0ZTRlZGQ5M2E3ODk0NGQyYzBiZDJlZTFhMTcyOTE0NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7zJb8XWV5KdBNVuslf90XawRSO2blLMIMIcJnBuL6rA)
> 
> ![Screen Shot 2023-11-24 at 17 11 37](https://private-user-images.githubusercontent.com/78159236/285447086-23c20b1d-0f64-49ba-91b2-423c0e0c3e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwODYtMjNjMjBiMWQtMGY2NC00OWJhLTkxYjItNDIzYzBlMGMzZTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ODdkMDRkN2FhYTI5ZDY4Njc4NTdjYjRhYzVlNzBkZGYzZDFlY2M4NGUzMDkwYmMyZGRhMTI0ODAwNTlmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HISzSzesWdtX-bGriz6i-i7wuYolxHLTEsAK3_2h_ys)
> 
> ![Screen Shot 2023-11-24 at 17 11 41](https://private-user-images.githubusercontent.com/78159236/285447089-3eb7bc59-a44f-41d3-9c15-d643eff4cf4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwODktM2ViN2JjNTktYTQ0Zi00MWQzLTljMTUtZDY0M2VmZjRjZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYTY5OTU3M2E0ZWRjYzU4MWMxZGE3YjZiZDUzZmRjMGRlZjFjMGZkOGU5MWZhMzcwMGEwZWU0YzUxN2RhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xAF6_-FZNOqbbMAtSn1QlX1Kgsw1PYeq-7L1ptutFwg)
> 
> ![Screen Shot 2023-11-24 at 17 11 46](https://private-user-images.githubusercontent.com/78159236/285447096-3b894362-e177-4580-a8c7-545ca8f16f97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcwOTYtM2I4OTQzNjItZTE3Ny00NTgwLWE4YzctNTQ1Y2E4ZjE2Zjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZDgyNDI4M2JiM2M3NGZjNDVkZjljOWI2NWIxYzMxNDhkZTFiZjY3ZWQyMmFjMzA4NmIyMGNhMTUyOGFmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ju8SfPSXPO2HPc8CZcsap510jpJW1155CmOPqf6D5Z8)
> 
> ![Screen Shot 2023-11-24 at 17 11 50](https://private-user-images.githubusercontent.com/78159236/285447102-c5b12608-b54d-44e5-9b68-2f7b1c2e6a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcxMDItYzViMTI2MDgtYjU0ZC00NGU1LTliNjgtMmY3YjFjMmU2YThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMDQyZmQ1MzgwZmJkNzI2YjY0ODA3YzIzMTVjZWU2NGI2MTM4NTI2MjUzZGJhYTM3Y2M2YTk1NmE0MzQxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GO7yiiPfBwGaAZoVBkM4ybXjzQi8vW-qKKAL8sAQtUc)
> 
> ![Screen Shot 2023-11-24 at 17 10 59](https://private-user-images.githubusercontent.com/78159236/285447105-5bf4d8a7-ebda-4392-b06e-0bb7595cbec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcxMDUtNWJmNGQ4YTctZWJkYS00MzkyLWIwNmUtMGJiNzU5NWNiZWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNjNmN2E2MGE5NjFjYjM2MzMwZDQ1ZjA5OTg2YWQxZmJlZTJkZjBiZjMzMzM4YjRjMDMxMzc2MmJkNzA5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ETSnufedAUF-K4V3EBuM37lxsvdeE7Z_DYsCZt_z5rM)
> 
> ![Screen Shot 2023-11-24 at 17 10 48](https://private-user-images.githubusercontent.com/78159236/285447109-69565050-f1ab-4fe9-9e5b-57897c55a7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcxMDktNjk1NjUwNTAtZjFhYi00ZmU5LTllNWItNTc4OTdjNTVhN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ODI4ZDQ5NzcxZDc4NmEwOGQ3ZDhlZGJlMzZiZDU0NmM2ODJkMGQ1ZTU2NmQ0ZTUzMmNmYWQ5Mjc3NTAwM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bNo-YCrpUCnuqoRBfrBr1wbae2Cn3AkGy3wj98rs90Y)
> 
> ![Screen Shot 2023-11-24 at 17 10 52](https://private-user-images.githubusercontent.com/78159236/285447116-22210f07-505f-4c02-bc45-9f3b2531492f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQyMDcsIm5iZiI6MTcwODE0MzkwNywicGF0aCI6Ii83ODE1OTIzNi8yODU0NDcxMTYtMjIyMTBmMDctNTA1Zi00YzAyLWJjNDUtOWYzYjI1MzE0OTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDA0MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTA2MGM3OGJiOWUxNDdiOTRiN2I3MmJiNDdmZjBiMWNkYmMwNjAxMzhjMTg1OTFjNmVjOTY4MDRlZDY3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Igf9DjGknRt-NIzWyyp-K0pKw3HkliGkAYWQNS4uqpM)

The UI and color palettes are looking cool!

**Comment by prjctimg** [comment]
Stale issue message
